# App Engine runtime configuration
runtime: custom
env: flex

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
# entrypoint: serve gae-app.php

# Defines static handlers to serve WordPress assets
handlers:
- url: /(.*\.(htm|html|css|js))
  static_files: \1
  upload: .*\.(htm|html|css|js)$

- url: /wp-content/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: wp-content/\1
  upload: wp-content/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: \1
  upload: .*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$

- url: /wp-includes/images/media/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
  static_files: wp-includes/images/media/\1
  upload: wp-includes/images/media/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$

beta_settings:
  cloud_sql_instances: project:region:instance

env_variables:
  CLOUD_SQL_INSTANCE: "project:region:instance"
  WORDPRESS_DB_HOST: "127.0.0.1"
  WORDPRESS_DB_NAME: "dolcestrings_wp"
  WORDPRESS_DB_USER: "dolcestrings_wp"
  WORDPRESS_DB_PASSWORD: "passwordHere"
  WORDPRESS_AUTH_KEY: 'authKey'
  WORDPRESS_SECURE_AUTH_KEY: 'secureKey'
  WORDPRESS_LOGGED_IN_KEY: 'loggedinKey'
  WORDPRESS_NONCE_KEY: 'nonceKey'
  WORDPRESS_AUTH_SALT: 'authSalt'
  WORDPRESS_SECURE_AUTH_SALT: 'secureauthKey'
  WORDPRESS_LOGGED_IN_SALT: 'loggedinSalt'
  WORDPRESS_NONCE_SALT: 'noneSalt'
