version: '3.1'
services:
  dolcestrings:
    build:
        context: .
        dockerfile: wordpress.Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
      - ./errors.ini:/usr/local/etc/php/conf.d/errors.ini 
      - ./mariadb_root_password:/tmp/mariadb_root_password
    environment:
      WORDPRESS_DB_HOST: dolcestrings_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: dolcestrings
      WORDPRESS_DB_PASSWORD_FILE: /tmp/mariadb_root_password
    restart: always
  dolcestrings_db:
    build:
        context: .
        dockerfile: mariadb.Dockerfile
    volumes:
        - ./mariadb-data:/var/lib/mysql
        - ./mariadb_root_password:/tmp/mariadb_root_password
    environment:
      MYSQL_DATABASE: dolcestrings
      MYSQL_ROOT_PASSWORD_FILE: /tmp/mariadb_root_password
    restart: always
  dolcestrings_cron:
    build:
      context: .
      dockerfile: cron.Dockerfile
    volumes:
        - ./mariadb-data:/var/lib/mysql
        - ./mariadb_root_password:/tmp/mariadb_root_password
    environment:
      MYSQL_DATABASE: dolcestrings
      MYSQL_ROOT_PASSWORD_FILE: /tmp/mariadb_root_password
    restart: always