version: '3.2'
services:
  app:
    build:
      context: .
      args:
        _WP_DB_HOST: "127.0.0.1"
        _WP_DB_USER: dolcestrings_wp
        _WP_DB_NAME: dolcestrings_wp
        _WP_DB_PASSWORD: <insert_password_here>
        _WP_THEMES: hhttps://storage.googleapis.com/dolcestrings-wp-media/showcase.zip
        _WP_PLUGINS: classic-editor wp-stateless crop-thumbnails easy-digital-downloads featured-video-plus pirate-forms testimonials-for-wp themeisle-companion wp-mail-smtp
        _CLOUDSQL_INSTANCE: "dolcestrings:australia-southeast1:mysql"
        _SERVICE_ACCOUNT_FILE: service-account.json
    environment: 
      PORT: 3000
    ports:
      - 3000:3000
    restart: always