version: '3.1'
services:
  dolcestrings:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 3000:8080
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini 
      - ./mariadb_root_password:/tmp/mariadb_root_password
    environment:
      CLOUD_SQL_INSTANCE: ""
      PORT: 8080
      WORDPRESS_DB_HOST: dolcestrings_db
      WORDPRESS_DB_USER: dolcestrings
      WORDPRESS_DB_NAME: dolcestrings_wp
      WORDPRESS_DB_PASSWORD_FILE: /tmp/mariadb_root_password
      WORDPRESS_THEMES: hestia
      WORDPRESS_PLUGINS: wp-stateless crop-thumbnails easy-digital-downloads featured-video-plus pirate-forms testimonials-for-wp themeisle-companion wp-mail-smtp
    restart: always
  dolcestrings_db:
    image: mariadb:latest
    volumes:
        - ./mariadb-data:/var/lib/mysql
        - ./mariadb_root_password:/tmp/mariadb_root_password
    environment:
      MYSQL_DATABASE: dolcestrings_wp
      MYSQL_USER: dolcestrings
      MYSQL_PASSWORD_FILE: /tmp/mariadb_root_password
      MYSQL_ROOT_PASSWORD_FILE: /tmp/mariadb_root_password
    restart: always